export const refreshTokenResponseExample = {
  refreshToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJ1c2VybmFtZTEyMyIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzIwNzk1NDYwLCJleHAiOjE3MjMzODc0NjB9.Ht3CaeNlUIX8qwyAo5DvD9uRoIA5DNc87GGIqkgveqQ',
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJ1c2VybmFtZTEyMyIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzIwNzk1NDYwLCJleHAiOjE3MjA3OTcyNjB9.BxQH3rm19lzPKSM2SCngPWsTGekvi2NpgyjkbupY1y4',
};
